const DEFAULT_NUMBER_VALIDATION_OPTIONAL = {
    type: Number,
    trim: true,
};

const DEFAULT_NUMBER_VALIDATION = {
    ...DEFAULT_NUMBER_VALIDATION_OPTIONAL,
    required: true,
};

export { DEFAULT_NUMBER_VALIDATION, DEFAULT_NUMBER_VALIDATION_OPTIONAL };